version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile
      args:
        DEBUG_ARG: true
    container_name: drota2_web
    volumes:
      - .:/app 
    ports:
      - '8080:8080'

  postgresql:
    image: postgres:17.5 
    container_name: drota2_postgresql 
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres 
      